### ISSUE TITLE
Terraform plan triggers an error

### ISSUE THREAD

**Issue by Thumpermat** [datawire/reference-infrastructure-fabric#3]
When I run the “terraform plan” command I get the following error :

  ```
Error: Error running plan: 1 error(s) occurred:

* module.main_network.output.external_subets: Resource 'aws_subnet.external' not found for variable 'aws_subnet.external.*'
```
I tried to add an elastic IP into the file “Variables.tf” for the subnet external (as xxx.xxx.xxx.xxx/32) but that didn’t change anything. I also tried to change region from eu-west-1 to us-east-2, same issue.

Any help will be appreciated.

**Comment by plombardi89** [comment]
Hi! What version of Terraform are you using `terraform version`? It's quite possible the way Terraform processes things has changed since when this guide was published and now (I believe I used 0.8.x).

**Comment by Thumpermat** [comment]
Hi,

I have used the last version (0.11.1), but I will try with the older version. 

Thank you very much for your reply.

If I can help you debug with the newest version, let me know. 

Or is the project dead ?

**Comment by plombardi89** [comment]
Dead is the wrong word... it needs to be updated and maintained better. The core mechanics are just as valid today as they were twelve months ago but the software used has clearly changed and we haven't kept up with documentation.

At the publication time this was a sanitized and cleaned up for public consumption version of our own infrastructure definition. Since then a lot has changed and we've learned a lot and changed a lot as well. I think we're due for a `v2`. For example, I'm not using Terraform anymore to handle the cluster provisioning and instead I let `kops` do it directly because the `kops` project has become a lot more stable and robust since early 2017 and I find the Terraform bit unnecessary. Also when I started building I had a belief I would need to hook into the Terraform state for other infrastructure tasks... and that just hasn't been the case.

**Comment by Thumpermat** [comment]
FYI, using Terraform 0.9.3 works.

Quite a few things have changed in Terraform, so this project would need a brush up.

Our goal is to set up a HA cluster on AWS for a customer. What I like very much with your approach is the automation of the VPC.

Will close the issue and I’m looking forward to your version 2.

**Comment by compiaffe** [comment]
@plombardi89 Great idea to have such a production quality demo setup. I've also run into a few issues due to changed interfaces and decided to go with a basic setup for now. Looking forward to an updated version.
